name: Build and Deploy to VM

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-virtual-machine:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.202
    # Trusts the HTTPS certificate
    - name: Dotnet trust HTTPS
      run: dotnet dev-certs https --trust
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish DDDProject/DDDProject.csproj -c Release -o release
    # runs the published project
    - name: Run .NET project
      run: |
          dotnet run DDDProject/DDDProject.csproj
          exec bash
