name: Build and Deploy to VM

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.202
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish DDDProject.csproj -c Release -o release
