name: My First YAML!

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  open-git-on-a-virtual-machine:
    # Use unbuntu latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses Github's checkout action to checkout code from the master branch
    - uses: actions/checkout@v2
